Less attachment to program args
This is now OK:
prettypipe bash -c 'printf hi'

It used to require:
prettypipe bash -- -c 'printf hi'
because -c was taken as an argument to prettypipe.

Otherwise you'd see from clap:
error: Found argument '-c' which wasn't expected, or isn't valid in this context

https://docs.rs/clap/2.33.3/clap/enum.AppSettings.html#variant.TrailingVarArg